### ISSUE TITLE
Update comment about ClojureScript

### ISSUE THREAD

**Issue by idibidiart** [anko/eslisp#10]
<<
ClojureScript is a heavy approach; a full Clojure compiler targeting JavaScript. Unlike eslisp, it requires the JVM and totally overrides JS' semantics.

ClojureScript can be self hosted now, so it will run in the browser without compilation.

https://github.com/swannodette/cljs-bootstrap

**Comment by anko** [comment]
Cool, didn't know of cljs-bootstrap.

It looks in-progress though. From [their readme, section _Usage_](https://github.com/swannodette/cljs-bootstrap#usage):

> Note currently only trivial expressions work. Arbitrary source code requires macro support which has not yet landed in ClojureScript master

Do you know more about that?

**Comment by idibidiart** [comment]
I think that is reference to the currently limited macro capability, but you can run all ClojureScript in the browser today! There is even a REPL based on that. Correct me if I'm wrong:)

**Comment by anko** [comment]
Limited macro capability means it's not quite all of ClojureScript! :wink:

I'll add a note about it to the comparison.

**Comment by idibidiart** [comment]
Right. I think eslisp, despite lacking ClojureScripts very powerful data manipulation capabilities, is an interesting addition to the JS ecosystem... it may make reasoning about algorithms a lot simpler, but may also become a thing of acquired taste. Great work btw... I love that someone did this.

**Comment by anko** [comment]
Thanks, that means a lot to me. :)
