### ISSUE TITLE
suggestion: rename `=` to `var`

### ISSUE THREAD

**Issue by lhorie** [anko/eslisp#15]
I think `(var a 1)` and `(var a)` read closer to their intent than `(= a 1)` and `(= a)`

Also, ES6 has `let`, so including a `let` macro into eslisp later would be more orthogonal if the hoisted declaration identifier is `var`

And that would free up the `=` identifier so you could use that for assignment instead of `:=`, to keep things closer to js syntax

**Comment by anko** [comment]
I agree—those should be the defaults.

The current names are remnants from when it hadn't quite clicked yet that I wanted eslisp to just clearly map to JS.

**Comment by anko** [comment]
In v0.5.0. :sparkles:
