### ISSUE TITLE
Source maps?

### ISSUE THREAD

**Issue by anko** [anko/eslisp#18]
Requested by @impinball and @Paraknight on separate occasions.

Source maps are supplementary info attached to JS code that lets debuggers point at what other-language file some piece of JavaScript was compiled from, so humans can find what to debug. [More here](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/).

Related to #9, as both require a way to track where in the input source an internal AST node came from.

**Comment by avesus** [comment]
:+1:

**Comment by anko** [comment]
While not _absolutely perfect_, the source maps as merged in 337a95a are pretty much correct.

Sample visualisation (using [this tool](http://sokra.github.io/source-map-visualization) made by [Tobias Koppers](https://github.com/sokra)):

![flyby of a visualisation](https://cloud.githubusercontent.com/assets/5231746/11407084/dc5a2df2-93b0-11e5-9d72-f5c75d665156.gif)

:tada::balloon:
