### ISSUE TITLE
How to convert JS into eslisp syntax?

### ISSUE THREAD

**Issue by reverofevil** [anko/eslisp#26]
I would like to reimplement some infrastructure like `browserify` over eslisp syntax, because it's common for such utilities to have imperative API that is very hard to extend, and I don't trust their conversion methods. But this would require not only JS pretty printer, but a JS parser too.

Is there already such an utility?

**Comment by anko** [comment]
There's no JS → eslisp [decompiler](https://en.wikipedia.org/wiki/Decompiler), if that's what you mean.

It might be possible to write a decompiler, using [esprima](http://esprima.org/) to parse JavaScript into an [estree](https://github.com/estree/estree) object and writing logic that does the inverse of the [built-in macros](https://github.com/anko/eslisp/blob/master/src/built-in-macros.ls), and producing eslisp code. However, it could only easily produce "core" eslisp code that uses the built-in macros (which match 1-to-1 with JavaScript). Anything else would take fairly substantial work on pattern matching.

I'm unsure what you mean by the browserify comparison. Could you elaborate?

**Comment by anko** [comment]
Closing this for now, because I'm unclear on what you meant.

This sounded interesting though—if you could clarify, I'll reopen.
