### ISSUE TITLE
(- 3 2 1) !== 3 - (2 - 1)

### ISSUE THREAD

**Issue by iovdin** [anko/eslisp#49]
I expect `(- 3 2 1)` to be translated to `3 - 2 - 1` which evaluates to `0` in javascript
while `3 - (2 - 1)` evaluates to `2` 

im to fix it

**Comment by anko** [comment]
What an embarrassing mistake. I forgot about [associativity](https://en.wikipedia.org/wiki/Operator_associativity)! Commit 2c48d06 should make [the appropriate operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) left-associative.

Should work as you expect in v0.7.5.
