### ISSUE TITLE
`return` requires an argument

### ISSUE THREAD

**Issue by alandipert** [anko/eslisp#53]
In Javascript, `return;` in a function returns `undefined`

In eslisp, the built-in `return` macro requires an argument, so returning without a value requires writing `(return undefined)`

**Comment by anko** [comment]
Thanks for catching that!

I've published `0.7.6` which should fix `return` to allow zero arguments. ([Demo here](https://runkit.com/anko/597dc1102bb82e0014ab8df5).)

**Comment by alandipert** [comment]
Thanks for fixing!
